// Available Bible versions for each language
export const availableVersions = {
    en: [
        { code: 'WEB', name: 'World English Bible' },
        { code: 'KJV', name: 'King James Version' },
        { code: 'ASV', name: 'American Standard Version' },
        { code: 'YLT', name: "Young's Literal Translation" },
        { code: 'BSB', name: 'Berean Standard Bible' },
    ],
    es: [
        { code: 'RV1960', name: 'Reina-Valera 1960' },
        { code: 'LBLA', name: 'La Biblia de las Américas' },
        { code: 'NVI', name: 'Nueva Versión Internacional' },
        { code: 'RV2004', name: 'Reina Valera Gómez 2004' },
        { code: 'PDT', name: 'Palabra de Dios para Todos' },
    ],
};

export const translations = {
    en: {
        title: 'Daily Bible Verse',
        newVerse: 'New Verse',
        loading: 'Loading verse...',
        error: 'Failed to load verse',
        tryAgain: 'Try Again',
        share: 'Share',
        copy: 'Copy',
        copied: 'Verse copied to clipboard!',
        shared: 'Verse shared successfully!',
        favorites: 'Favorites',
        viewFavorites: 'View Favorites',
        noFavorites: 'No favorite verses yet',
        addFavorite: 'Add to favorites',
        removeFavorite: 'Remove from favorites',
        back: 'Back',
        language: 'Language',
        theme: 'Theme',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        downloadedBooks: 'Downloaded Books',
        viewBooks: 'View Books',
        noBooks: 'No books downloaded yet',
        downloadBook: 'Download Book',
        selectBook: 'Select a Book',
        downloading: 'Downloading...',
        downloadComplete: 'Book downloaded!',
        deleteBook: 'Delete',
        chapters: 'chapters',
        selectLanguage: 'Select Language',
        selectVersion: 'Select Version',
        english: 'English',
        spanish: 'Spanish',
    },
    es: {
        title: 'Versículo Bíblico Diario',
        newVerse: 'Nuevo Versículo',
        loading: 'Cargando versículo...',
        error: 'Error al cargar versículo',
        tryAgain: 'Intentar de nuevo',
        share: 'Compartir',
        copy: 'Copiar',
        copied: '¡Versículo copiado al portapapeles!',
        shared: '¡Versículo compartido exitosamente!',
        favorites: 'Favoritos',
        viewFavorites: 'Ver Favoritos',
        noFavorites: 'Aún no hay versículos favoritos',
        addFavorite: 'Agregar a favoritos',
        removeFavorite: 'Quitar de favoritos',
        back: 'Volver',
        language: 'Idioma',
        theme: 'Tema',
        light: 'Claro',
        dark: 'Oscuro',
        system: 'Sistema',
        downloadedBooks: 'Libros Descargados',
        viewBooks: 'Ver Libros',
        noBooks: 'No hay libros descargados aún',
        downloadBook: 'Descargar Libro',
        selectBook: 'Seleccionar un Libro',
        downloading: 'Descargando...',
        downloadComplete: '¡Libro descargado!',
        deleteBook: 'Eliminar',
        chapters: 'capítulos',
        selectLanguage: 'Seleccionar idioma',
        selectVersion: 'Seleccionar versión',
        english: 'Inglés',
        spanish: 'Español',
    },
};

// Bible books with their chapter counts
export const bibleBooks = [
    { name: 'Genesis', chapters: 50, spanish: 'Génesis' },
    { name: 'Exodus', chapters: 40, spanish: 'Éxodo' },
    { name: 'Leviticus', chapters: 27, spanish: 'Levítico' },
    { name: 'Numbers', chapters: 36, spanish: 'Números' },
    { name: 'Deuteronomy', chapters: 34, spanish: 'Deuteronomio' },
    { name: 'Joshua', chapters: 24, spanish: 'Josué' },
    { name: 'Judges', chapters: 21, spanish: 'Jueces' },
    { name: 'Ruth', chapters: 4, spanish: 'Rut' },
    { name: '1 Samuel', chapters: 31, spanish: '1 Samuel' },
    { name: '2 Samuel', chapters: 24, spanish: '2 Samuel' },
    { name: '1 Kings', chapters: 22, spanish: '1 Reyes' },
    { name: '2 Kings', chapters: 25, spanish: '2 Reyes' },
    { name: '1 Chronicles', chapters: 29, spanish: '1 Crónicas' },
    { name: '2 Chronicles', chapters: 36, spanish: '2 Crónicas' },
    { name: 'Ezra', chapters: 10, spanish: 'Esdras' },
    { name: 'Nehemiah', chapters: 13, spanish: 'Nehemías' },
    { name: 'Esther', chapters: 10, spanish: 'Ester' },
    { name: 'Job', chapters: 42, spanish: 'Job' },
    { name: 'Psalms', chapters: 150, spanish: 'Salmos' },
    { name: 'Proverbs', chapters: 31, spanish: 'Proverbios' },
    { name: 'Ecclesiastes', chapters: 12, spanish: 'Eclesiastés' },
    { name: 'Song of Solomon', chapters: 8, spanish: 'Cantares' },
    { name: 'Isaiah', chapters: 66, spanish: 'Isaías' },
    { name: 'Jeremiah', chapters: 52, spanish: 'Jeremías' },
    { name: 'Lamentations', chapters: 5, spanish: 'Lamentaciones' },
    { name: 'Ezekiel', chapters: 48, spanish: 'Ezequiel' },
    { name: 'Daniel', chapters: 12, spanish: 'Daniel' },
    { name: 'Hosea', chapters: 14, spanish: 'Oseas' },
    { name: 'Joel', chapters: 3, spanish: 'Joel' },
    { name: 'Amos', chapters: 9, spanish: 'Amós' },
    { name: 'Obadiah', chapters: 1, spanish: 'Abdías' },
    { name: 'Jonah', chapters: 4, spanish: 'Jonás' },
    { name: 'Micah', chapters: 7, spanish: 'Miqueas' },
    { name: 'Nahum', chapters: 3, spanish: 'Nahúm' },
    { name: 'Habakkuk', chapters: 3, spanish: 'Habacuc' },
    { name: 'Zephaniah', chapters: 3, spanish: 'Sofonías' },
    { name: 'Haggai', chapters: 2, spanish: 'Hageo' },
    { name: 'Zechariah', chapters: 14, spanish: 'Zacarías' },
    { name: 'Malachi', chapters: 4, spanish: 'Malaquías' },
    { name: 'Matthew', chapters: 28, spanish: 'Mateo' },
    { name: 'Mark', chapters: 16, spanish: 'Marcos' },
    { name: 'Luke', chapters: 24, spanish: 'Lucas' },
    { name: 'John', chapters: 21, spanish: 'Juan' },
    { name: 'Acts', chapters: 28, spanish: 'Hechos' },
    { name: 'Romans', chapters: 16, spanish: 'Romanos' },
    { name: '1 Corinthians', chapters: 16, spanish: '1 Corintios' },
    { name: '2 Corinthians', chapters: 13, spanish: '2 Corintios' },
    { name: 'Galatians', chapters: 6, spanish: 'Gálatas' },
    { name: 'Ephesians', chapters: 6, spanish: 'Efesios' },
    { name: 'Philippians', chapters: 4, spanish: 'Filipenses' },
    { name: 'Colossians', chapters: 4, spanish: 'Colosenses' },
    { name: '1 Thessalonians', chapters: 5, spanish: '1 Tesalonicenses' },
    { name: '2 Thessalonians', chapters: 3, spanish: '2 Tesalonicenses' },
    { name: '1 Timothy', chapters: 6, spanish: '1 Timoteo' },
    { name: '2 Timothy', chapters: 4, spanish: '2 Timoteo' },
    { name: 'Titus', chapters: 3, spanish: 'Tito' },
    { name: 'Philemon', chapters: 1, spanish: 'Filemón' },
    { name: 'Hebrews', chapters: 13, spanish: 'Hebreos' },
    { name: 'James', chapters: 5, spanish: 'Santiago' },
    { name: '1 Peter', chapters: 5, spanish: '1 Pedro' },
    { name: '2 Peter', chapters: 3, spanish: '2 Pedro' },
    { name: '1 John', chapters: 5, spanish: '1 Juan' },
    { name: '2 John', chapters: 1, spanish: '2 Juan' },
    { name: '3 John', chapters: 1, spanish: '3 Juan' },
    { name: 'Jude', chapters: 1, spanish: 'Judas' },
    { name: 'Revelation', chapters: 22, spanish: 'Apocalipsis' },
];
