import { StyleSheet, Platform } from 'react-native';

export const createStyles = (isDark: boolean, isSmallDevice: boolean, isTablet: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: isDark ? '#1C1C1C' : '#F5F5F0',
        paddingTop: Platform.OS === 'ios' ? (isSmallDevice ? 50 : 60) : 40,
    },
    headerContainer: {
        paddingHorizontal: isSmallDevice ? 15 : isTablet ? 30 : 20,
        paddingBottom: isSmallDevice ? 15 : 20,
        alignItems: 'center',
    },
    header: {
        paddingHorizontal: isSmallDevice ? 15 : isTablet ? 30 : 20,
        paddingBottom: isSmallDevice ? 15 : 20,
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    headerButtons: {
        flexDirection: 'row',
        gap: 10,
    },
    iconButton: {
        padding: 8,
    },
    iconButtonText: {
        fontSize: isSmallDevice ? 18 : 20,
    },
    backButton: {
        padding: 8,
        alignSelf: 'flex-start',
        marginBottom: 5,
        marginLeft: -8, // Negative margin to align text with padding
    },
    backButtonText: {
        fontSize: 16,
        color: isDark ? '#8B7355' : '#4A5D4E',
        fontWeight: '600',
    },
    title: {
        fontSize: isSmallDevice ? 20 : isTablet ? 28 : 24,
        fontWeight: 'bold',
        color: isDark ? '#F5F5F0' : '#2C2C2C',
        marginBottom: 10,
        textAlign: 'center',
        alignSelf: 'center',
        width: '100%',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: isSmallDevice ? 20 : isTablet ? 60 : 30,
    },
    verseContainer: {
        maxHeight: '50%',
        marginBottom: 20,
    },
    verseText: {
        fontSize: isSmallDevice ? 18 : isTablet ? 24 : 20,
        lineHeight: isSmallDevice ? 28 : isTablet ? 38 : 32,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        textAlign: 'center',
        marginBottom: 20,
    },
    reference: {
        fontSize: isSmallDevice ? 14 : isTablet ? 18 : 16,
        color: isDark ? '#8B7355' : '#4A5D4E',
        fontStyle: 'italic',
        textAlign: 'center',
        marginBottom: 10,
    },
    actionButtons: {
        flexDirection: 'row',
        gap: isSmallDevice ? 10 : 15,
        marginBottom: 20,
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    actionButton: {
        paddingVertical: isSmallDevice ? 8 : 10,
        paddingHorizontal: isSmallDevice ? 15 : 20,
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderRadius: 25,
        borderWidth: 1,
        borderColor: isDark ? '#444' : '#DDD',
    },
    actionButtonText: {
        fontSize: isSmallDevice ? 14 : 16,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
    },
    actionButtonSelected: {
        backgroundColor: isDark ? '#8B7355' : '#4A5D4E',
        borderColor: isDark ? '#8B7355' : '#4A5D4E',
    },
    actionButtonTextSelected: {
        color: '#FFFFFF',
    },
    button: {
        backgroundColor: isDark ? '#8B7355' : '#4A5D4E',
        paddingVertical: isSmallDevice ? 12 : 15,
        paddingHorizontal: isSmallDevice ? 30 : 40,
        borderRadius: 25,
        marginTop: 10,
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: isSmallDevice ? 16 : 18,
        fontWeight: '600',
    },
    bottomButtons: {
        marginTop: 20,
        flexDirection: isSmallDevice ? 'column' : 'row',
        gap: isSmallDevice ? 10 : 20,
        alignItems: 'center',
    },
    viewFavoritesButton: {
        padding: 10,
    },
    viewFavoritesText: {
        color: isDark ? '#8B7355' : '#4A5D4E',
        fontSize: isSmallDevice ? 14 : 16,
        textDecorationLine: 'underline',
    },
    errorContainer: {
        alignItems: 'center',
    },
    errorText: {
        color: isDark ? '#E88B8B' : '#C44',
        fontSize: 16,
        marginBottom: 10,
        textAlign: 'center',
    },
    errorSubtext: {
        color: isDark ? '#888' : '#666',
        fontSize: 14,
        marginBottom: 20,
        textAlign: 'center',
    },
    favoritesContainer: {
        flex: 1,
        paddingHorizontal: isSmallDevice ? 15 : isTablet ? 40 : 20,
    },
    noFavoritesText: {
        color: isDark ? '#888' : '#666',
        fontSize: 16,
        textAlign: 'center',
        marginTop: 40,
    },
    favoriteItem: {
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: isDark ? '#444' : '#E0E0E0',
    },
    favoriteContent: {
        flex: 1,
    },
    favoriteVerse: {
        fontSize: isSmallDevice ? 14 : isTablet ? 18 : 16,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        marginBottom: 8,
        lineHeight: isSmallDevice ? 20 : isTablet ? 26 : 24,
    },
    favoriteReference: {
        fontSize: isSmallDevice ? 12 : isTablet ? 16 : 14,
        color: isDark ? '#8B7355' : '#4A5D4E',
        fontStyle: 'italic',
    },
    favoriteButton: {
        padding: 10,
    },
    favoriteIcon: {
        fontSize: 24,
    },
    downloadButton: {
        backgroundColor: isDark ? '#8B7355' : '#4A5D4E',
        paddingVertical: 15,
        paddingHorizontal: 40,
        borderRadius: 25,
        margin: 20,
        alignItems: 'center',
    },
    bookItem: {
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: isDark ? '#444' : '#E0E0E0',
    },
    bookItemContent: {
        flex: 1,
    },
    bookItemTitle: {
        fontSize: isSmallDevice ? 16 : isTablet ? 20 : 18,
        fontWeight: '600',
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        marginBottom: 4,
    },
    bookItemSubtitle: {
        fontSize: isSmallDevice ? 12 : isTablet ? 16 : 14,
        color: isDark ? '#888' : '#666',
    },
    deleteButton: {
        padding: 10,
    },
    deleteButtonText: {
        fontSize: 20,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dropdownModal: {
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderRadius: 12,
        minWidth: 200,
        padding: 8,
    },
    modalContent: {
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '80%',
        paddingBottom: 40,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: isDark ? '#444' : '#E0E0E0',
    },
    modalTitle: {
        fontSize: isSmallDevice ? 18 : isTablet ? 22 : 20,
        fontWeight: '600',
        color: isDark ? '#E8E8E8' : '#2C2C2C',
    },
    modalSubtitle: {
        fontSize: 14,
        color: isDark ? '#AAA' : '#666',
        marginBottom: 12,
        paddingHorizontal: 20,
        textAlign: 'center',
    },
    modalCloseButton: {
        fontSize: 24,
        color: isDark ? '#888' : '#666',
        fontWeight: '300',
    },
    bookList: {
        padding: 20,
    },
    versionList: {
        padding: 20,
    },
    bookListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 20,
        backgroundColor: isDark ? '#1C1C1C' : '#F5F5F0',
        borderRadius: 10,
        marginBottom: 10,
    },
    bookListItemDisabled: {
        opacity: 0.5,
    },
    bookListItemText: {
        fontSize: 16,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        fontWeight: '500',
    },
    bookListItemTextDisabled: {
        color: isDark ? '#666' : '#999',
    },
    bookListItemChapters: {
        fontSize: 14,
        color: isDark ? '#888' : '#666',
    },
    modalOption: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginBottom: 4,
    },
    modalOptionSelected: {
        backgroundColor: isDark ? '#8B7355' : '#4A5D4E',
    },
    modalOptionText: {
        fontSize: 16,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        fontWeight: '500',
    },
    modalOptionTextSelected: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    modalDivider: {
        height: 1,
        backgroundColor: isDark ? '#444' : '#E0E0E0',
        marginVertical: 8,
    },
    versionButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: isDark ? '#8B7355' : '#4A5D4E',
        marginTop: 4,
    },
    versionButtonText: {
        fontSize: 16,
        color: isDark ? '#8B7355' : '#4A5D4E',
        textAlign: 'center',
        fontWeight: '600',
    },
    downloadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    downloadingText: {
        color: '#FFFFFF',
        fontSize: 18,
        marginTop: 20,
        fontWeight: '600',
    },
    bookContent: {
        flex: 1,
        paddingHorizontal: 20,
    },
    bookVerseCard: {
        backgroundColor: isDark ? '#2C2C2C' : '#FFFFFF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: isDark ? '#444' : '#E0E0E0',
    },
    bookVerse: {
        marginBottom: 30,
    },
    bookVerseText: {
        fontSize: isSmallDevice ? 14 : isTablet ? 18 : 16,
        lineHeight: isSmallDevice ? 22 : isTablet ? 28 : 26,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        marginBottom: 10,
    },
    bookVerseReference: {
        fontSize: isSmallDevice ? 12 : isTablet ? 16 : 14,
        color: isDark ? '#8B7355' : '#4A5D4E',
        fontStyle: 'italic',
        marginBottom: 12,
    },
    bookVerseActions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 10,
    },
    bookVerseActionButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: isDark ? '#1C1C1C' : '#F5F5F0',
        borderRadius: 8,
        alignItems: 'center',
    },
    bookVerseActionText: {
        fontSize: isSmallDevice ? 12 : 14,
        color: isDark ? '#E8E8E8' : '#2C2C2C',
        fontWeight: '500',
    },
    progressContainer: {
        marginTop: 4,
    },
    progressBar: {
        height: 8,
        backgroundColor: isDark ? '#444' : '#E0E0E0',
        borderRadius: 4,
        overflow: 'hidden',
        marginBottom: 6,
    },
    progressFill: {
        height: '100%',
        borderRadius: 4,
    },
    progressText: {
        fontSize: 12,
        color: isDark ? '#888' : '#666',
        fontWeight: '600',
    },
});
